### ISSUE TITLE
Missing donate button ;)

### ISSUE THREAD

**Issue by jlaustill** [LinxGem33/OSX-Arc-Darker#1]
You made the exact theme I wanted for my gnome install, it's awesome.  I'd like to buy you a coffee, but there's no donate button.  I consider this a show stopper bug lol.

**Comment by LinxGem33** [comment]
@jlaustill 

I really appreciate your feed back, i do this to give back to the community and your appreciation is absolutely enough.  :)

**Comment by jlaustill** [comment]
Well ok then :). Thanks a ton, love your work!
