### ISSUE TITLE
Window borders Elementary OS authentication screens

### ISSUE THREAD

**Issue by golden1988** [LinxGem33/OSX-Arc-Darker#11]
I installed the theme on elementary os. There is only a problem with the window borders on elementary OS. 
The authentication screen has a window border, in the original theme this isnt there .  Can u remove that windowborder?
I've added screenshots.
![original](https://user-images.githubusercontent.com/31272661/29605621-dccd50b2-87eb-11e7-9e5d-c0876da97765.png)

![window border](https://user-images.githubusercontent.com/31272661/29605598-be7566b8-87eb-11e7-8c5e-6e967764f180.png)

**Comment by LinxGem33** [comment]
appreciate the feed back this is normal as osx arc darker is based on arc darker which also has the borders, ill look into it on the next release cycle.

kind regards
