### ISSUE TITLE
Alert dialogs are still light

### ISSUE THREAD

**Issue by elegos** [LinxGem33/OSX-Arc-Darker#12]
Hello!

I've noticed that the alert dialogs are still of a light color... is this supposed to be like so?

![image](https://user-images.githubusercontent.com/577975/29960609-ab62d3e0-8efc-11e7-8a8a-5c0a129eafb0.png)

**Comment by LinxGem33** [comment]
yes. it is normal behaviour.

kind regards

**Comment by Alkaris** [comment]
for a theme that has "Darker" in its name this is just the opposite of "Darker" if you have white in it.
