### ISSUE TITLE
Problem with latest chrome version

### ISSUE THREAD

**Issue by flolivaud** [LinxGem33/OSX-Arc-Darker#16]
Only when chrome is maximized, the green button is missing. 
[see here](https://i.imgur.com/CRfjOYz.png)

**Comment by mexico66** [comment]
Same problem here. 
![chrome-maximized](https://user-images.githubusercontent.com/10914709/33683535-8c25f26c-dacb-11e7-9a0a-c6457e272225.png)

**Comment by mexico66** [comment]
Problem solved with Chrome 63. Now it's ok.

**Comment by LinxGem33** [comment]
thanks for letting us know.
