### ISSUE TITLE
Not an issue, just a question.

### ISSUE THREAD

**Issue by nuno-azevedo** [LinxGem33/OSX-Arc-Darker#17]
Sorry to open an issue just for asking a question, but I didn't find any other way to contact you.

Can you please tell me how could you make your panel icons like this?

![screenshot from 2017-10-30 01-20-30](https://user-images.githubusercontent.com/19556475/32151014-4d780e92-bd11-11e7-90b9-bf8dbd8996ba.png)

All of the same size and really like OSX ones, I am trying to do this for a long time.

**Comment by LinxGem33** [comment]
sorry for the late reply ... regarding your question its really simple just install the icon theme which i preconfigured and created for the osx arc collection.

the link is below:
https://github.com/LinxGem33/Arc-OSX-Icons
