### ISSUE TITLE
GNOME crashes when loading OSX-Arc user theme on Debian Jessie 8.7.1.

### ISSUE THREAD

**Issue by tranhl** [LinxGem33/OSX-Arc-Darker#2]
I've just attempted to install your theme on a fresh install of Debian Jessie, 8.7.1. I've updated the gnome and gnome-themes-standard packages, and installed gtk2-engines-murrine. I am able to change the GTK+ theme and window theme, but when I enable the user themes extension, and select a user theme (in this case OSX-Arc-Darker), the desktop environment crashes and I'm left with a "Oh no! Something has gone wrong. A problem has occurred and the system can't recover. All extensions have been disabled as a precaution" message. I'm not exactly sure what is wrong, so any help you can give me to fix this would be appreciated. I do love the look of your theme, so I definitely want to fix this as soon as possible.

**Comment by LinxGem33** [comment]
@tranhl 
hi going by the information that you’ve supplied i don’t think its an issue with the theme rather an issue with your Debian build all i can suggest at this point is to do a manual install of the theme by extracting it to the icons folder, as i don’t use Debian Jessie 8.7.1 so i couldn’t speculate as to what the issue maybe, however from what you’ve said all dependences are installed so it should run smoothly also make sure you remove old themes before reinstalling and reboot your system.

kind regards

**Comment by tranhl** [comment]
Hi again. I remember running `apt dist-upgrade` when installing the murrine engine. During my install, I manually moved the each theme to the `/usr/share/themes` folder, but the same issue still persisted. This leads me to believe that the issue is with Debian Jessie itself, as the stable build will only allow me to upgrade to Gnome 3.14. I'm currently away from my system, so when I get back to it I'll edit this post with a log file to help you address the issue.
