### ISSUE TITLE
No padding space in Ubuntu 17.04

### ISSUE THREAD

**Issue by opensas** [LinxGem33/OSX-Arc-Darker#3]
When I install the theme using ubuntu 17.04 it seems like there's some kind of padding space between elements missing

I add two pictures comparing the results of Arc-dark with osx-ark-darker

$ uname -a
Linux ubuntu 4.10.0-20-generic #22-Ubuntu SMP Thu Apr 20 09:22:42 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

![arc-dark](https://cloud.githubusercontent.com/assets/481687/26042104/c1167c4a-3908-11e7-92aa-968f1de0c276.png)
![osx-arc-dark](https://cloud.githubusercontent.com/assets/481687/26042103/c114d2d2-3908-11e7-9c0e-2b7ad29f6a8e.png)

**Comment by LinxGem33** [comment]
@opensas 

appreciate the feedback, ill look into the issue and hopefully have a fix for the next point release.
kind regards

**Comment by LinxGem33** [comment]
please test the latest version and let me know if the issue still persists.

kind regards

**Comment by opensas** [comment]
It works great!!! :-)

![screenshot from 2017-06-04 23-03-11](https://cloud.githubusercontent.com/assets/481687/26768205/a0691668-497c-11e7-83e3-820b8141c795.png)
