### ISSUE TITLE
gnome-terminal tabs color

### ISSUE THREAD

**Issue by kedwin** [LinxGem33/OSX-Arc-Darker#9]
using Arch linux
gnome-terminal tab colors are white

i did try to modfy a bit the css if that helps
`
terminal-window {
  border: 0;
}
terminal-window header tabs:checked {
  border: 2px solid red;
}

terminal-window header, terminal-window tabs {
  background-color: #404552;
  color: #D3DAE3;
}

terminal-window header label {
 color: #D3DAE3;
}

terminal-window header tabs tab:checked{
  background-color: #404552;
  border: 0;
}

`

![screenshot from 2017-08-10 15-31-17](https://user-images.githubusercontent.com/10922690/29172687-04f0fde2-7de1-11e7-9e60-4c00aacba205.png)

**Comment by LinxGem33** [comment]
make sure you have all dependencies installed you can find them on the main page and also pixbuf package.

kind regards

**Comment by LinxGem33** [comment]
closed due to lack of response.
